---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory2/hosts.yaml"
    group_file: "inventory2/groups.yaml"
    defaults_file: "inventory2/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 100